Login screen
knowitrickard/FlexiCharge-iOS pull request #30
Opened 2021-09-13 16:59 UTC by filipfloden

Fixes #6 

# Description

This PR implements the login screen which will be used to login users when we have access the API for it.

## Lists of changes

- [x] Overall design
- [x] TextField for email input
- [x] SecureField for password input
- [x] Log in button
- [x] Forgot password text which is meant to be embedded in a NavigationLink when the Recover password page is made.

![image](https://user-images.githubusercontent.com/48211957/133125523-54f0bc75-e293-48ef-9e85-da5fdefed92f.png)

## Testing

Short summary of what should be tested
- [ ] See if the email & password fields placeholder works. Should be moved to overlap the top border
- [ ] See if the design looks fine on different size devices

2021-09-15 10:40 UTC, Yevve requested changes
Add a test account validation for login so it can be used in transition testing.

2021-09-15 11:31 UTC, scamdivine approved these changes

2021-09-15 11:31 UTC, scamdivine commented on FlexiCharge/FlexiCharge/Views/Login/LoginView.swift
> +                    Text(emailPlaceholder)
one .something on each line plzy

2021-09-15 11:43 UTC, filipfloden commented
> Add a test account validation for login so it can be used in transition testing.

Daniel suggested that. we just make the login button redirect to the startpage when we combine all the register/login views. I think we should go with this idea!

2021-09-16 22:33 UTC, Yevve approved these changes
LGTM!

2021-09-17 06:31 UTC, merged