Design on settings page #10
knowitrickard/FlexiCharge-iOS pull request #45
Opened 2021-09-20 11:59 UTC by scamdivine

Fixes #10 
Fixes the Settings view to look like the given mockups
A summary explaining what changes the PR has made.

- [ ] added logout button
- [ ] Added navigation links to all new pages 
- [ ] Created custom backbutton 

<img width="358" alt="Skärmavbild 2021-09-20 kl  13 56 29" src="https://user-images.githubusercontent.com/72702048/133998163-a684277f-88ff-404d-b68a-2c074371255a.png">

Short summary of what should be tested
- [ ] Make sure the settings view looks good on different screens 
- [ ] test fancy back button

2021-09-21 08:39 UTC, LucasStrand requested changes
There's something off about the **Profile & settings** text along with where the back button is geographically placed on the vertical axis. Tweak it a tad bit further down, I believe, should fix it.
Also, while you're at it, and if you feel like it, you can add the fancy back button accordingly to all views that should have it. I know we have some back buttons that are the un modified one. 
Aaaaaalso, if you decide to have a custom placement for the text, tweak the other title texts as well so we have unity in where the text is placed <3 this is of course applied to font size as well.

Great work otherwise! 🥇

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                    // Change navigationling to correct page once it is created
navigationling 🇨🇳

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                    // Change navigationling to correct page once it is created
navigationling 🍚

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                    // Change navigationling to correct page once it is created
navigationling 🍜

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        }.frame(width: screenWidth * 0.8, height: screenHeight*0.05, alignment: .bottom)
space 👨🏻‍🚀

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        }.frame(width: screenWidth * 0.8, height: screenHeight*0.05, alignment: .bottom)
📡 🛰️

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        }.frame(width: screenWidth * 0.8, height: screenHeight*0.05, alignment: .bottom)
🚀 ⭐ 🌔

2021-09-21 08:39 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        }.frame(width: screenWidth * 0.8, height: screenHeight*0.05, alignment: .bottom)
yeah, i think you get it at this point

2021-09-21 08:40 UTC, LucasStrand commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        }.frame(width: screenWidth * 0.8, height: screenHeight*0.05, alignment: .bottom)
be consistent with spaces `screenHeight*0.05,`

2021-09-22 12:44 UTC, LucasStrand approved these changes
🦸🏻

2021-09-22 12:45 UTC, filipfloden commented
The line underneath each row should not be all the way to the edges. Please fix this.

2021-09-22 12:59 UTC, filipfloden requested changes

2021-09-22 12:59 UTC, filipfloden commented on FlexiCharge/FlexiCharge/Views/Settings/SettingsView.swift
> +                        .background(Color(red: 0.90, green: 0.90, blue: 0.90))
Refer to comment above

2021-09-23 20:16 UTC, filipfloden approved these changes
Nice work!

2021-09-23 20:19 UTC, merged